name: wrotto
description: Open Source Journal App with Calender, Map View and stats.

publish_to: 'none'

version: 0.5.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # UI
  fluttertoast: ^7.1.6
  table_calendar: ^2.3.3
  latlong: ^0.6.1
  fl_chart: ^0.12.2
  # zefyr: ^0.12.0

  # maps
  flutter_map: ^0.9.0
  nominatim_location_picker: ^0.1.0+7
  osm_nominatim: ^1.0.1
  location: ^3.2.4

  # Services
  sqflite: ^1.3.2+3
  shared_preferences: ^0.5.12+4
  provider: ^4.3.3

  # utils
  vibration: ^1.7.3
  file_picker: 2.0.0
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  url_launcher: ^5.7.10

  # security
  local_auth: ^0.6.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "file-assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/text.png